/**
 * `dim generate-context` (KARPATHY_LAYERS Feature 1) — Environment layer.
 *
 * Renders the repo's trustworthy memory (VERIFIED + UNVERIFIED + pinned, never
 * STALE/REFUTED) into the static context file that non-MCP AI tools read at
 * session start: CLAUDE.md, .cursorrules, .windsurfrules, AGENTS.md, or
 * .github/copilot-instructions.md.
 *
 * This is what makes aidimag useful to *every* AI tool, not just MCP clients.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import type { MemoryStore } from "../db/store.js";
import type { GuardrailLevel, MemoryEntry, MemoryKind } from "../types.js";
import type { ContextFormat } from "../config.js";

const GENERATED_HEADER = "aidimag — do not edit manually; regenerate with `dim generate-context`";

/** Files written per format. `all` writes every target. */
const FORMAT_FILES: Record<Exclude<ContextFormat, "all">, string> = {
  claude: "CLAUDE.md",
  cursorrules: ".cursorrules",
  copilot: path.join(".github", "copilot-instructions.md"),
  windsurfrules: ".windsurfrules",
  agents: "AGENTS.md",
};

const GUARDRAIL_ICON: Record<GuardrailLevel, string> = {
  never: "🚫 NEVER",
  always: "✅ ALWAYS",
  "ask-first": "🤚 ASK FIRST",
};

interface Section {
  kind: MemoryKind;
  heading: string;
}

// Order matters: guardrails + failed approaches are the highest-signal sections.
const SECTIONS: Section[] = [
  { kind: "GUARDRAIL", heading: "Guardrails ⚠️" },
  { kind: "DECISION", heading: "Decisions" },
  { kind: "CONVENTION", heading: "Conventions" },
  { kind: "INVARIANT", heading: "Invariants" },
  { kind: "ARCHITECTURE", heading: "Architecture" },
  { kind: "GOTCHA", heading: "Gotchas" },
  { kind: "SKILL", heading: "Skills (reusable procedures)" },
  { kind: "FAILED_APPROACH", heading: "Failed Approaches (don't retry these)" },
  { kind: "TODO_CONTEXT", heading: "Open Context (unfinished work)" },
];

function statusTag(m: MemoryEntry): string {
  const bits = [m.status === "VERIFIED" ? "VERIFIED" : m.status];
  if (m.pinned) bits.push("📌");
  return `[${bits.join(" ")}]`;
}

/** SKILL claims often embed "1) … 2) …" steps — render them as an ordered list. */
function renderSkill(m: MemoryEntry): string {
  const steps = m.claim.split(/\s*\d+\)\s+/).map((s) => s.trim()).filter(Boolean);
  if (steps.length < 2) return `- ${m.claim} ${statusTag(m)}`;
  const [title, ...rest] = m.claim.includes(":") ? [m.claim.split(":")[0]] : [""];
  const head = title ? `**${title.trim()}** ${statusTag(m)}` : statusTag(m);
  const items = (title ? steps.slice(1) : steps).map((s, i) => `  ${i + 1}. ${s}`);
  return `- ${head}\n${items.join("\n")}`;
}

function renderGuardrail(m: MemoryEntry): string {
  const level = m.guardrailLevel ?? "ask-first";
  return `- ${GUARDRAIL_ICON[level]}: ${m.claim} ${statusTag(m)}`;
}

function renderMemory(m: MemoryEntry): string {
  if (m.kind === "GUARDRAIL") return renderGuardrail(m);
  if (m.kind === "SKILL") return renderSkill(m);
  const scope = m.scope.paths.length ? ` _(scope: ${m.scope.paths.join(", ")})_` : "";
  return `- ${m.claim}${scope} ${statusTag(m)}`;
}

/** Pinned first, then by confidence desc — the most load-bearing memory leads. */
function sortForContext(a: MemoryEntry, b: MemoryEntry): number {
  if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
  return b.confidence - a.confidence;
}

export interface RenderResult {
  markdown: string;
  total: number;
  pinned: number;
}

/** Build the markdown body shared by all output formats. */
export function renderContext(store: MemoryStore): RenderResult {
  const memories = store
    .list(10_000)
    .filter((m) => m.status === "VERIFIED" || m.status === "UNVERIFIED");
  const pinned = memories.filter((m) => m.pinned).length;

  const lines: string[] = [
    `<!-- ${GENERATED_HEADER} -->`,
    `# Project Memory`,
    `> Auto-generated by aidimag · ${new Date().toISOString()} · ${memories.length} memories, ${pinned} pinned`,
    "",
    "Treat the items below as the project's verified beliefs. Respect every **Guardrail**:",
    "🚫 NEVER = refuse and explain why · ✅ ALWAYS = do it without asking · 🤚 ASK FIRST = check with the user first.",
    "",
  ];

  for (const section of SECTIONS) {
    const items = memories.filter((m) => m.kind === section.kind).sort(sortForContext);
    if (!items.length) continue;
    lines.push(`## ${section.heading}`, ...items.map(renderMemory), "");
  }

  if (memories.length === 0) {
    lines.push("_No verified memories yet — run `dim remember` or approve proposals with `dim review`._", "");
  }

  return { markdown: lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n", total: memories.length, pinned };
}

function targetsFor(format: ContextFormat): Array<Exclude<ContextFormat, "all">> {
  return format === "all" ? ["claude", "cursorrules", "copilot", "windsurfrules", "agents"] : [format];
}

export interface WriteResult extends RenderResult {
  files: string[];
}

/** Render + write the configured context file(s). Returns repo-relative paths written. */
export function generateContext(store: MemoryStore, repoRoot: string, format: ContextFormat = "claude"): WriteResult {
  const rendered = renderContext(store);
  const files: string[] = [];
  for (const target of targetsFor(format)) {
    const rel = FORMAT_FILES[target];
    const abs = path.join(repoRoot, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, rendered.markdown);
    files.push(rel);
  }
  return { ...rendered, files };
}

